.*: Assembler messages:
.*: Error: unrecognized form of instruction `grev s0,s1'
.*: Error: unrecognized form of instruction `grevi s0,s1'
.*: Error: unrecognized form of instruction `shfl s0,s1'
.*: Error: junk at end of line, first unrecognized character is `0'
.*: Error: unrecognized form of instruction `unshfl s0,s1'
.*: Error: unrecognized form of instruction `shfli t0,t1'
.*: Error: junk at end of line, first unrecognized character is `0'
.*: Error: unrecognized form of instruction `unshfli t0,t1'
