.*: Assembler messages:
.*: Error: unrecognized form of instruction `crc32.b s0,s1,s2'
.*: Error: unrecognized form of instruction `crc32.h s0,s1,s2'
.*: Error: unrecognized form of instruction `crc32.w s0,s1,s2'
.*: Error: unrecognized form of instruction `crc32c.b s0,s1,s2'
.*: Error: unrecognized form of instruction `crc32c.h s0,s1,s2'
.*: Error: unrecognized form of instruction `crc32c.w s0,s1,s2'
